country =
{
	tag						= U91
	capital					= 1039
	# research_mod			= 0.5

	manpower				= 10
	energy					= 1000
	metal					= 1000
	rare_materials			= 500
	oil						= 1000
	supplies				= 100
	money					= 20
	belligerence 			= 0
	transports				= 0
	escorts					= 0

	diplomacy =
	{
#		relation			= { tag = ### value = 100 }
	}

	SpyInfo					= { country = "U91" NumberOfSpies = 1 }
	
	policy =
	{
		date				= { year = 0 month = january day = 0 }
		democratic			= 4
		political_left		= 4
		freedom				= 5 
		free_market			= 6
		professional_army	= 1 
		defense_lobby		= 7
		interventionism		= 2
	}

	techapps =
	{
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310
#SW Tank 
7600 7610
#Great War Infantry Division  
1010  1020 1030 1040 1050 1060 
#Interbellum 1930 Supply 
1910 1920 1930 1940 1950 1960
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160  1170 1180 1190 1200 1210 1220 1230 1240
#Engineers
1830 1840
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Modern Agriculture  
5700 5710 5010
#Improved Construction Engineering 
5800 5080 
#Basic Oil Refining 
#5190 

#Medicine
5600 5610
#Troopships
3810

# Great War Land Doctrines (entente)
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
	}

	blueprints				= { 81880 81890 }
	inventions				= { 3000027 }

	peacetime_ic_mod		= 0.8
	# wartime_ic_mod			= 0.9

	headofstate				= { type = 9 id = 1270001 }
	headofgovernment		= { type = 9 id = 1270002 }
	foreignminister			= { type = 9 id = 1270003 }
	armamentminister		= { type = 9 id = 1270004 }
	ministerofsecurity		= { type = 9 id = 1270005 }
	ministerofintelligence	= { type = 9 id = 1270006 }
	chiefofstaff			= { type = 9 id = 1270007 }
	chiefofarmy				= { type = 9 id = 1270008 }
	chiefofnavy				= { type = 9 id = 1270009 }
	chiefofair				= { type = 9 id = 1270010 }

	nationalprovinces =
	{
		# Middle East
		1038 1039 1043
	}

	ownedprovinces =
	{
		# Middle East
		1039 1043
	}

	controlledprovinces =
	{
		# Middle East
		1039 1043
	}

	claimedprovinces =
	{
	}
}