country =
{
	tag						= ETH
	capital					= 833
	# research_mod			= 0.5

	manpower				= 10
	energy					= 1000
	metal					= 1000
	rare_materials			= 500
	oil						= 1000
	supplies				= 100
	money					= 20
	belligerence 			= 0
	transports				= 0
	escorts					= 0

	diplomacy =
	{
#		relation			= { tag = ### value = 100 }
	}

	SpyInfo					= { country = "ETH" NumberOfSpies = 10 }
	
	policy =
	{
		date				= { year = 0 month = january day = 0 }
		democratic			= 1
		political_left		= 1
		freedom				= 1 
		free_market			= 1
		professional_army	= 1 
		defense_lobby		= 1
		interventionism		= 1
	}

	techapps =
	{
		# Infantry
		1010 1020 1030 1040 1050 1060
	}

	blueprints				= { 81880 81890 }
	inventions				= { 3000027 }

	peacetime_ic_mod		= 0.8
	# wartime_ic_mod			= 0.9

	headofstate				= { type = 9 id = 25001 }
	headofgovernment		= { type = 9 id = 25002 }
	foreignminister			= { type = 9 id = 25003 }
	armamentminister		= { type = 9 id = 25004 }
	ministerofsecurity		= { type = 9 id = 25005 }
	ministerofintelligence	= { type = 9 id = 25006 }
	chiefofstaff			= { type = 9 id = 25007 }
	chiefofarmy				= { type = 9 id = 25008 }
	chiefofnavy				= { type = 9 id = 25009 }
	chiefofair				= { type = 9 id = 25010 }

	nationalprovinces =
	{
		# Ethiopia
		815  816  817  818  819  820  821  822  823  824
		825  826  827  828  829  830  831

		# Horn of Africa
		832  833  834  835  836  837  838

		# East Africa
		839  842 852
	}

	ownedprovinces =
	{
		# Ethiopia
		815  816  817  818  819  820  821  822  823  824
		825  826  827  828  831

		# Horn of Africa
		832  833  834  835  836  837  838

		# East Africa
		839  842 852
	}

	controlledprovinces =
	{
		# Ethiopia
		815  816  817  818  819  820  821  822  823  824
		825  826  827  828  831

		# Horn of Africa
		832  833  834  835  836  837  838

		# East Africa
		839  842 852
	}

	claimedprovinces =
	{
	}
}