 
 ############################## 
 # Country definition for BUL # 
 ############################## 
  

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = BUL 
   ai = "default.ai"
   dissent = 20
   # Resource Reserves 
energy                 = 1500
metal                  = 750
rare_materials         = 375
   oil                    = 500 
   supplies               = 500 
   money                  = 50 
   manpower               = 0 
   capital                = 318 
   transports             = 10 
   escorts                = 4 
   diplomacy = 
   {  relation = {  tag = GRE value = -200  } 

    } 
   SpyInfo                = {  country = "BUL" NumberOfSpies = 6  } 
   nationalprovinces      = {   307 317 318 319 320 321 322 323 324 325 326 364 370 
             #Macedonia and Greece 
             328 333 363 365 366 
              } 
   ownedprovinces         = {  318  } #poor bulgaria
   controlledprovinces    = {  318  }
   claimedprovinces = { 331 334 } 
   
	# Eastern Minor Tech '36 
	# Group D 1936 techs 
	# ###################### 
	techapps               = {  

	# Manufacturing
	5810 5820 5050 5830
	# Construction Engineering 
	5800 5080 5090 
	# Agriculture  
	5700 5710 5010
	# Computers & cryptography
	5310 54010 54020 54030 5316 5326
	# Medicine
	5600 5610 5620

	# Infantry Division  
	1010 1020 1030 1040 1050 1060 
	# Mountain Division 
	1160 1170 1180 1190 1200 1210 1220 1230
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350
	# Engineers
	1830 1840 1850 
	# Supply 
	1910 1920 1930 1940 1950 1960

	# Tanks
	7600 7610 2620 2010 2630 2640
	# Armoured Car  
	2860 2870 2880 
	# Field Artillery 
	2290 2300 2310 2900 2910
	# Static Anti-Air Artillery 
	2800 2450 21180 
	# Anti-Air Artillery Brigade 
	2810 2820 

	# Hospital System
	14000 14010
	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
	# Grand Battle Plan Doctrine
	6560
	
	# Destroyers
	3010
	# Torpedo & ASW 18
	3720 3730 3900
	#Troopships
	3810

	# Naval Doctrines
	8010 8020 8050 
	
	# Interceptor Fighter
	4500 4510 4520 4530 4540 4550 4010
	# Multirole Fighter
	4300 4310 4320 4330
	# Tactical Bomber
	4600 4610 4620 4630 4120
	# Strategic Bomber
	4800 4810 
	# Naval Bomber
	4700 4710

	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470
	
	} 

inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 3 
     political_left    = 4 
     free_market       = 7 
     freedom           = 6 
     professional_army = 2 
     defense_lobby     = 5 
     interventionism   = 9 
    } 
   headofstate            = {  type = 9 id = 95001  } 
   headofgovernment       = {  type = 9 id = 95002  } 
   foreignminister        = {  type = 9 id = 95003  } 
   armamentminister       = {  type = 9 id = 95004  } 
   ministerofsecurity     = {  type = 9 id = 95005  } 
   ministerofintelligence = {  type = 9 id = 95006  } 
   chiefofstaff           = {  type = 9 id = 95007  } 
   chiefofarmy            = {  type = 9 id = 95008  } 
   chiefofnavy            = {  type = 9 id = 95009  } 
   chiefofair             = {  type = 9 id = 95010  } 
   # Firepower 

  } 
 