 
 ############################## 
 # Country definition for SRB # 
 ############################## 
  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = SER 
   ai = "default.ai"
   dissent = 20
   # Resource Reserves 
energy                 = 1500
metal                  = 750
rare_materials         = 375
   transports = 50
   oil                    = 500 
   supplies               = 500 
   money                  = 15 
   capital                = 338 
   manpower 			  = 24
      
   diplomacy = 
   { 
     relation = 
     {  tag        = ITA 
       value      = 100 
      } 
    } 
   SpyInfo                = {  country = "SER" NumberOfSpies = 7  } 
   nationalprovinces      = {  338 339 340 342 327 330 335 354 353 357 358 355 356 331 329 } 
   ownedprovinces         = { 338 339 340 342 327 330 335 354 353 357 358 355 356 331 329  } 
   controlledprovinces    = { 338 339 340 342 327 330 335 354 353 357 358 355 356 331 329  } 
   # Eastern Minor Tech '36 
   # Group D 1936 techs 
   # ###################### 
   # GW fighter 
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310
#SW Tank 
7600 7610 2620 2010
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160 1170 1180 1190 1200 1210 1220 1230 1240
#Engineers
1830 1840 
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Modern Agriculture  
5700 5710 5010
#Manufactoring
5810 5820 5050 5830
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Improved Construction Engineering 
5800 5080 5090 
#Basic Oil Refining 
#5190
#Interwar Bomber 
4600 4610 4620 4630 4120
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Short Range Submarine 
3610 3620
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600 5610 #5620
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Naval Doctrines
8010 8040 8050
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Land doctrines WWI - Entente line
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Landdoctrine ww2 - none?
#Improved Great War Hospital System
14000 #14010
} 
inventions = { 3000027 }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 4 
     political_left    = 3 
     freedom           = 5 
     free_market       = 5 
     professional_army = 5 
     defense_lobby     = 4 
     interventionism   = 6 
    } 
	peacetime_ic_mod       = 0.6 # 0.8 	
   headofstate            = {  type = 9 id = 100086  } #Aleksandar I
   headofgovernment       = {  type = 9 id = 100002  } 
   foreignminister        = {  type = 9 id = 100003  } 
   armamentminister       = {  type = 9 id = 100004  } 
   ministerofsecurity     = {  type = 9 id = 100005  } 
   ministerofintelligence = {  type = 9 id = 100006  } 
   chiefofstaff           = {  type = 9 id = 100007  } 
   chiefofarmy            = {  type = 9 id = 100008  } 
   chiefofnavy            = {  type = 9 id = 100009  } 
   chiefofair             = {  type = 9 id = 100010  } 

  } 
 
