country =
{
	tag						= TIB
	capital					= 1289
	# research_mod			= 0.6

	manpower				= 15
	energy					= 1000
	metal					= 900
	rare_materials			= 400
	oil						= 300
	supplies				= 300
	money					= 10
	belligerence 			= 0
	transports				= 0
	escorts					= 0
	
	diplomacy =
	{
	}
	
	SpyInfo					= { country = "TIB" NumberOfSpies = 4 }

	policy =
	{
		date				= { year = 0 month = january day = 0 }
		democratic			= 3
		political_left		= 4
		freedom				= 5
		free_market			= 5
		professional_army	= 1
		defense_lobby		= 1
		interventionism		= 1
	}

	techapps				= { 2150 2290 1010 1190 }

	headofstate				= { type = 9 id = 73001 }
	headofgovernment		= { type = 9 id = 73002 }
	foreignminister			= { type = 9 id = 73003 }
	armamentminister		= { type = 9 id = 73004 }
	ministerofsecurity		= { type = 9 id = 73005 }
	ministerofintelligence	= { type = 9 id = 73006 }
	chiefofstaff			= { type = 9 id = 73007 }
	chiefofarmy				= { type = 9 id = 73008 }
	chiefofnavy				= { type = 9 id = 73009 }
	chiefofair				= { type = 9 id = 73010 }

	nationalprovinces =
	{
		1275 1274 1278 1279 1282 1286 1287 1288 1289 1290
		1295
	}

	ownedprovinces =
	{
		1275 1274 1278 1279 1282 1286 1287 1288 1289 1290
		1295
	}

	controlledprovinces =
	{
		1275 1274 1278 1279 1282 1286 1287 1288 1289 1290
		1295
	}

	claimedprovinces =
	{
	}
}